"""Initial_db

Revision ID: 668a687d77e4
Revises: e52aa4542b61
Create Date: 2023-11-12 17:10:03.956233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668a687d77e4'
down_revision = 'e52aa4542b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_cinema',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('cinema_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'cinema_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('film_cinema')
    op.drop_table('cinema')
    # ### end Alembic commands ###
