"""Added cinema_id to Film

Revision ID: a1d3a9727d0b
Revises: 668a687d77e4
Create Date: 2023-11-13 19:06:52.625739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d3a9727d0b'
down_revision = '668a687d77e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('film_cinema')  # Comentado o eliminado si no es necesario
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cinema_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_film_cinema', 'cinema', ['cinema_id'], ['id'])  # Asignar nombre a la FK

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_constraint('fk_film_cinema', type_='foreignkey')  # Usar el nombre asignado a la FK
        batch_op.drop_column('cinema_id')

    # Restaurar la tabla 'film_cinema' si es necesario
    # Si no se necesita, puedes comentar o eliminar este bloque de código
    #op.create_table('film_cinema',
    #sa.Column('film_id', sa.INTEGER(), nullable=False),
    #sa.Column('cinema_id', sa.INTEGER(), nullable=False),
    #sa.ForeignKeyConstraint(['cinema_id'], ['cinema.id'], ),
    #sa.ForeignKeyConstraint(['film_id'], ['film.id'], ),
    #sa.PrimaryKeyConstraint('film_id', 'cinema_id')
    #)
    # ### end Alembic commands ###